### ISSUE TITLE
TurtleCoin.proto comments

### ISSUE THREAD

**Issue by LeTurt** [turtlecoin/t2t-protocol#1]
The current version of this file seems to be based on the CN code implementation, which is OK but I think some improvements might be possible. The CN devs seem to like to put in a lot of abstraction where not always needed.

I tried to read the CN transaction standard for this to get some terminology: https://cryptonote.org/cns/cns004.txt. Hope I got it right.

My suggestions:

base transaction: 
this seems to be a name for a transaction that generates new coins. maybe the name comes from coinbase transaction?

but does it need a separate data type? in the end, it is just a transaction without signature.

TurtleTransactionPrefix vs TurtleTransaction vs TurtleTransactionSignature. Do these serve any purpose to separate? How about just TurtleTransaction with all of them?

Same for blocks.

signatures could perhaps be better represented by byte arrays, since those are what they are actually? the CN code just calls their datatype a string but uses it as a byte array as well.

in input, does it need separate types, since there is the type flag already?

as for outputs, it seems to me that there is really only one output type, so does it need the type id? block versioning can be used to add one if needed i guess. 

see CryptoNoteSerialization.cpp the function

    void getVariantValue(CryptoNote::ISerializer &serializer, uint8_t tag, CryptoNote::TransactionOutputTarget &out)

has 

            case 0x2:
            {
                CryptoNote::KeyOutput v;
                serializer(v, "data");
                out = v;
                break;
            }
            default:
                throw std::runtime_error("Unknown variant tag");

of course, don't trust me reading that code to get it right. I never do.

maybe it could then look something like this:

    // Copyright (c) 2018, The TurtleCoin Developers
    // 
    // Please see the included LICENSE file for more information.

    syntax = "proto3";

    package t2t;

    message TurtleBlock {
      uint32 majorVersion = 1;
      uint32 minorVersion = 2;
      uint64 timestamp = 3;
      string previousBlockHash = 4;
      uint32 nonce = 5;
      TurtleTransaction baseTransaction = 6;
      repeated TurtleTransaction transactions = 7;
    }

    message TurtleTransaction {
      uint32 version = 1;
      uint64 unlockTime = 2;
      repeated TurtleTransactionInput inputs = 3;
      repeated TurtleTransactionOutput outputs = 4;
      string paymentId = 5;
      bytes extra = 6;
      repeated bytes signature = 7;
    }

    message TurtleTransactionInput {
      int32 type = 1;
      uint64 amount = 2;
      repeated uint32 offsets = 3;
      bytes keyImage = 4;
    }

    message TurtleTransactionOutput {
      uint64 amount = 1;
      bytes target = 2;
    }

I think I was trying to write something like this when trying to parse the packets from current version in turtlegod. transaction.go, cryptonote_notes.md.

comments, opinions, ... ?

**Comment by brandonlehmann** [comment]
This "project" is being abandoned in favor of *almost* anything else.
